package sap_api_output_formatter

type Header struct {
	Code                        string      `json:"Code"`
	EffectiveStartDate          string      `json:"EffectiveStartDate"`
	BusinessUnit                string      `json:"BusinessUnit"`
	LastModifiedDateTime        string      `json:"LastModifiedDateTime"`
	JobTitle                    string      `json:"JobTitle"`
	Criticality                 string      `json:"Criticality"`
	CreatedDateTime             string      `json:"CreatedDateTime"`
	JobCode                     string      `json:"JobCode"`
	MdfSystemVersionID          string      `json:"MdfSystemVersionID"`
	Type                        string      `json:"Type"`
	Incumbent                   string      `json:"Incumbent"`
	Division                    string      `json:"Division"`
	ExternalNameZhTW            string      `json:"ExternalNameZhTW"`
	ExternalNameJaJP            string      `json:"ExternalNameJaJP"`
	MdfSystemEntityID           string      `json:"MdfSystemEntityID"`
	PayRange                    string      `json:"PayRange"`
	RegularTemporary            string      `json:"RegularTemporary"`
	ExternalNamePtPT            string      `json:"ExternalNamePtPT"`
	CostCenter                  string      `json:"CostCenter"`
	StandardHours               string      `json:"StandardHours"`
	LegacyPositionID            string      `json:"LegacyPositionID"`
	ExternalNameZhCN            string      `json:"ExternalNameZhCN"`
	ExternalNameLocalized       string      `json:"ExternalNameLocalized"`
	MdfSystemRecordStatus       string      `json:"MdfSystemRecordStatus"`
	Vacant                      bool        `json:"Vacant"`
	EffectiveStatus             string      `json:"EffectiveStatus"`
	ExternalNameFrFR            string      `json:"ExternalNameFrFR"`
	TechnicalParameters         string      `json:"TechnicalParameters"`
	ExternalNameEnGB            string      `json:"ExternalNameEnGB"`
	EffectiveEndDate            string      `json:"EffectiveEndDate"`
	PositionCriticality         string      `json:"PositionCriticality"`
	ExternalNameNlNL            string      `json:"ExternalNameNlNL"`
	PositionTitle               string      `json:"PositionTitle"`
	Description                 string      `json:"Description"`
	ExternalNameDefaultValue    string      `json:"ExternalNameDefaultValue"`
	ExternalNameEsES            string      `json:"ExternalNameEsES"`
	PositionControlled          string      `json:"PositionControlled"`
	ExternalNamePtBR            string      `json:"ExternalNamePtBR"`
	PayGrade                    string      `json:"PayGrade"`
	Company                     string      `json:"Company"`
	Department                  string      `json:"Department"`
	EmployeeClass               string      `json:"EmployeeClass"`
	MdfSystemObjectType         string      `json:"MdfSystemObjectType"`
	CreationSource              string      `json:"CreationSource"`
	ChangeReason                string      `json:"ChangeReason"`
	TargetFTE                   string      `json:"TargetFTE"`
	LastModifiedDate            string      `json:"LastModifiedDate"`
	ExternalNameRuRU            string      `json:"ExternalNameRuRU"`
	LastModifiedBy              string      `json:"LastModifiedBy"`
	LastModifiedDateWithTZ      string      `json:"LastModifiedDateWithTZ"`
	JobLevel                    string      `json:"JobLevel"`
	TransactionSequence         string      `json:"TransactionSequence"`
	ExternalNameDeDE            string      `json:"ExternalNameDeDE"`
	ExternalNameKoKR            string      `json:"ExternalNameKoKR"`
	CreatedDate                 string      `json:"CreatedDate"`
	CreatedBy                   string      `json:"CreatedBy"`
	MdfSystemOptimisticLockUUID string      `json:"MdfSystemOptimisticLockUUID"`
	MdfSystemRecordID           string      `json:"MdfSystemRecordID"`
	Comment                     string      `json:"Comment"`
	Location                    string      `json:"Location"`
	MultipleIncumbentsAllowed   bool        `json:"MultipleIncumbentsAllowed"`
	ExternalNameEnUS            string      `json:"ExternalNameEnUS"`
	ExternalNameEnDEBUG         string      `json:"ExternalNameEnDEBUG"`
	RegularTemporaryNav         string      `json:"RegularTemporaryNav"`
	ExternalNameTranslationTextNav string   `json:"ExternalNameTranslationTextNav"`
	CompanyNav                  string      `json:"CompanyNav"`
	EffectiveStatusNav          string      `json:"EffectiveStatusNav"`
	DepartmentNav               string      `json:"DepartmentNav"`
	BusinessUnitNav             string      `json:"BusinessUnitNav"`
	LocationNav                 string      `json:"LocationNav"`
	CostCenterNav               string      `json:"CostCenterNav"`
	JobCodeNav                  string      `json:"JobCodeNav"`
	DivisionNav                 string      `json:"DivisionNav"`
	JobLevelNav                 string      `json:"JobLevelNav"`
	ParentPosition              string      `json:"ParentPosition"`
	PayGradeNav                 string      `json:"PayGradeNav"`
}

type RegularTemporaryNav struct {
	ExternalCode                 string      `json:"ExternalCode"`
	PickListV2EffectiveStartDate string      `json:"PickListV2EffectiveStartDate"`
	PickListV2ID                 string      `json:"PickListV2ID"`
	LabelNlNL                    string      `json:"LabelNlNL"`
	LastModifiedDateTime         string      `json:"LastModifiedDateTime"`
	MdfSystemEffectiveEndDate    string      `json:"MdfSystemEffectiveEndDate"`
	CreatedDateTime              string      `json:"CreatedDateTime"`
	MdfSystemVersionID           string      `json:"MdfSystemVersionID"`
	LabelEsES                    string      `json:"LabelEsES"`
	MaxVal                       string      `json:"MaxVal"`
	MinVal                       string      `json:"MinVal"`
	LabelPtBR                    string      `json:"LabelPtBR"`
	MdfSystemEntityID            string      `json:"MdfSystemEntityID"`
	LabelEnDEBUG                 string      `json:"LabelEnDEBUG"`
	NonUniqueExternalCode        string      `json:"NonUniqueExternalCode"`
	LegacyStatus                 string      `json:"LegacyStatus"`
	LabelRuRU                    string      `json:"LabelRuRU"`
	MdfSystemRecordStatus        string      `json:"MdfSystemRecordStatus"`
	LabelDefaultValue            string      `json:"LabelDefaultValue"`
	LabelEnUS                    string      `json:"LabelEnUS"`
	LabelDeDE                    string      `json:"LabelDeDE"`
	LabelLocalized               string      `json:"LabelLocalized"`
	LabelKoKR                    string      `json:"LabelKoKR"`
	OptionID                     string      `json:"OptionID"`
	Status                       string      `json:"Status"`
	OptValue                     string      `json:"OptValue"`
	LValue                       string      `json:"LValue"`
	MdfSystemEffectiveStartDate  string      `json:"MdfSystemEffectiveStartDate"`
	LabelZhTW                    string      `json:"LabelZhTW"`
	LabelJaJP                    string      `json:"LabelJaJP"`
	ExternalStandardizedCode     string      `json:"ExternalStandardizedCode"`
	MdfSystemObjectType          string      `json:"MdfSystemObjectType"`
	LabelPtPT                    string      `json:"LabelPtPT"`
	LastModifiedDate             string      `json:"LastModifiedDate"`
	LastModifiedBy               string      `json:"LastModifiedBy"`
	LastModifiedDateWithTZ       string      `json:"LastModifiedDateWithTZ"`
	LabelZhCN                    string      `json:"LabelZhCN"`
	RValue                       string      `json:"RValue"`
	MdfSystemTransactionSequence string      `json:"MdfSystemTransactionSequence"`
	CreatedDate                  string      `json:"CreatedDate"`
	CreatedBy                    string      `json:"CreatedBy"`
	ParentPickListValue          string      `json:"ParentPickListValue"`
	MdfSystemRecordID            string      `json:"MdfSystemRecordID"`
	LabelFrFR                    string      `json:"LabelFrFR"`
	LabelEnGB                    string      `json:"LabelEnGB"`
}

type ExternalNameTranslationTextNav struct {
	Locale string `json:"Locale"`
	Value  string `json:"Value"`
}

type CompanyNav struct {
	ExternalCode            string      `json:"ExternalCode"`
	StartDate               string      `json:"StartDate"`
	Country                 string      `json:"Country"`
	DescriptionKoKR         string      `json:"DescriptionKoKR"`
	LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
	NameLocalized           string      `json:"NameLocalized"`
	EndDate                 string      `json:"EndDate"`
	NameKoKR                string      `json:"NameKoKR"`
	CreatedDateTime         string      `json:"CreatedDateTime"`
	DescriptionPtBR         string      `json:"DescriptionPtBR"`
	DescriptionEsES         string      `json:"DescriptionEsES"`
	NamePtBR                string      `json:"NamePtBR"`
	DescriptionNlNL         string      `json:"DescriptionNlNL"`
	NameNlNL                string      `json:"NameNlNL"`
	StandardHours           string      `json:"StandardHours"`
	DescriptionDefaultValue string      `json:"DescriptionDefaultValue"`
	NameDeDE                string      `json:"NameDeDE"`
	NameZhTW                string      `json:"NameZhTW"`
	Name                    string      `json:"Name"`
	NameEsES                string      `json:"NameEsES"`
	DescriptionEnUS         string      `json:"DescriptionEnUS"`
	DescriptionEnDEBUG      string      `json:"DescriptionEnDEBUG"`
	DescriptionRuRU         string      `json:"DescriptionRuRU"`
	Status                  string      `json:"Status"`
	NameRuRU                string      `json:"NameRuRU"`
	DescriptionJaJP         string      `json:"DescriptionJaJP"`
	DescriptionFrFR         string      `json:"DescriptionFrFR"`
	NamePtPT                string      `json:"NamePtPT"`
	Description             string      `json:"Description"`
	DescriptionDeDE         string      `json:"DescriptionDeDE"`
	NameFrFR                string      `json:"NameFrFR"`
	NameEnDEBUG             string      `json:"NameEnDEBUG"`
	NameJaJP                string      `json:"NameJaJP"`
	CreatedOn               string      `json:"CreatedOn"`
	NameEnUS                string      `json:"NameEnUS"`
	Currency                string      `json:"Currency"`
	DescriptionZhTW         string      `json:"DescriptionZhTW"`
	NameZhCN                string      `json:"NameZhCN"`
	NameDefaultValue        string      `json:"NameDefaultValue"`
	DescriptionEnGB         string      `json:"DescriptionEnGB"`
	LastModifiedBy          string      `json:"LastModifiedBy"`
	DefaultPayGroup         string      `json:"DefaultPayGroup"`
	NameEnGB                string      `json:"NameEnGB"`
	LastModifiedOn          string      `json:"LastModifiedOn"`
	DescriptionZhCN         string      `json:"DescriptionZhCN"`
	CreatedBy               string      `json:"CreatedBy"`
	DescriptionLocalized    string      `json:"DescriptionLocalized"`
	DescriptionPtPT         string      `json:"DescriptionPtPT"`
	DefaultLocation         string      `json:"DefaultLocation"`
}

type EffectiveStatusNav struct {
	Value     string `json:"Value"`
	Key       string `json:"Key"`
	EnDEBUG   string `json:"EnDEBUG"`
	RuRU      string `json:"RuRU"`
	Localized string `json:"Localized"`
	PtBR      string `json:"PtBR"`
	FrFR      string `json:"FrFR"`
	JaJP      string `json:"JaJP"`
	DeDE      string `json:"DeDE"`
	EnGB      string `json:"EnGB"`
	ZhTW      string `json:"ZhTW"`
	KoKR      string `json:"KoKR"`
	EnUS      string `json:"EnUS"`
	EsES      string `json:"EsES"`
	ZhCN      string `json:"ZhCN"`
	NlNL      string `json:"NlNL"`
	PtPT      string `json:"PtPT"`
}

type DepartmentNav struct {
	ExternalCode            string      `json:"ExternalCode"`
	StartDate               string      `json:"StartDate"`
	Parent                  string      `json:"Parent"`
	DescriptionKoKR         string      `json:"DescriptionKoKR"`
	LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
	NameLocalized           string      `json:"NameLocalized"`
	EndDate                 string      `json:"EndDate"`
	EntityUUID              string      `json:"EntityUUID"`
	NameKoKR                string      `json:"NameKoKR"`
	CreatedDateTime         string      `json:"CreatedDateTime"`
	DescriptionPtBR         string      `json:"DescriptionPtBR"`
	DescriptionEsES         string      `json:"DescriptionEsES"`
	NamePtBR                string      `json:"NamePtBR"`
	DescriptionNlNL         string      `json:"DescriptionNlNL"`
	NameNlNL                string      `json:"NameNlNL"`
	CostCenter              string      `json:"CostCenter"`
	DescriptionDefaultValue string      `json:"DescriptionDefaultValue"`
	NameDeDE                string      `json:"NameDeDE"`
	NameZhTW                string      `json:"NameZhTW"`
	Name                    string      `json:"Name"`
	NameEsES                string      `json:"NameEsES"`
	DescriptionEnUS         string      `json:"DescriptionEnUS"`
	DescriptionEnDEBUG      string      `json:"DescriptionEnDEBUG"`
	DescriptionRuRU         string      `json:"DescriptionRuRU"`
	Status                  string      `json:"Status"`
	NameRuRU                string      `json:"NameRuRU"`
	DescriptionJaJP         string      `json:"DescriptionJaJP"`
	DescriptionFrFR         string      `json:"DescriptionFrFR"`
	NamePtPT                string      `json:"NamePtPT"`
	Description             string      `json:"Description"`
	DescriptionDeDE         string      `json:"DescriptionDeDE"`
	NameFrFR                string      `json:"NameFrFR"`
	NameEnDEBUG             string      `json:"NameEnDEBUG"`
	NameJaJP                string      `json:"NameJaJP"`
	CreatedOn               string      `json:"CreatedOn"`
	HeadOfUnit              string      `json:"HeadOfUnit"`
	NameEnUS                string      `json:"NameEnUS"`
	DescriptionZhTW         string      `json:"DescriptionZhTW"`
	NameZhCN                string      `json:"NameZhCN"`
	NameDefaultValue        string      `json:"NameDefaultValue"`
	DescriptionEnGB         string      `json:"DescriptionEnGB"`
	LastModifiedBy          string      `json:"LastModifiedBy"`
	NameEnGB                string      `json:"NameEnGB"`
	LastModifiedOn          string      `json:"LastModifiedOn"`
	DescriptionZhCN         string      `json:"DescriptionZhCN"`
	CreatedBy               string      `json:"CreatedBy"`
	DescriptionLocalized    string      `json:"DescriptionLocalized"`
	DescriptionPtPT         string      `json:"DescriptionPtPT"`
}

type BusinessUnitNav struct {
	ExternalCode            string      `json:"ExternalCode"`
	StartDate               string      `json:"StartDate"`
	DescriptionKoKR         string      `json:"DescriptionKoKR"`
	LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
	NameLocalized           string      `json:"NameLocalized"`
	EndDate                 string      `json:"EndDate"`
	EntityUUID              string      `json:"EntityUUID"`
	NameKoKR                string      `json:"NameKoKR"`
	CreatedDateTime         string      `json:"CreatedDateTime"`
	DescriptionPtBR         string      `json:"DescriptionPtBR"`
	DescriptionEsES         string      `json:"DescriptionEsES"`
	NamePtBR                string      `json:"NamePtBR"`
	DescriptionNlNL         string      `json:"DescriptionNlNL"`
	NameNlNL                string      `json:"NameNlNL"`
	DescriptionDefaultValue string      `json:"DescriptionDefaultValue"`
	NameDeDE                string      `json:"NameDeDE"`
	NameZhTW                string      `json:"NameZhTW"`
	Name                    string      `json:"Name"`
	NameEsES                string      `json:"NameEsES"`
	DescriptionEnUS         string      `json:"DescriptionEnUS"`
	DescriptionEnDEBUG      string      `json:"DescriptionEnDEBUG"`
	DescriptionRuRU         string      `json:"DescriptionRuRU"`
	Status                  string      `json:"Status"`
	NameRuRU                string      `json:"NameRuRU"`
	DescriptionJaJP         string      `json:"DescriptionJaJP"`
	DescriptionFrFR         string      `json:"DescriptionFrFR"`
	NamePtPT                string      `json:"NamePtPT"`
	Description             string      `json:"Description"`
	DescriptionDeDE         string      `json:"DescriptionDeDE"`
	NameFrFR                string      `json:"NameFrFR"`
	NameEnDEBUG             string      `json:"NameEnDEBUG"`
	NameJaJP                string      `json:"NameJaJP"`
	CreatedOn               string      `json:"CreatedOn"`
	HeadOfUnit              string      `json:"HeadOfUnit"`
	NameEnUS                string      `json:"NameEnUS"`
	DescriptionZhTW         string      `json:"DescriptionZhTW"`
	NameZhCN                string      `json:"NameZhCN"`
	NameDefaultValue        string      `json:"NameDefaultValue"`
	DescriptionEnGB         string      `json:"DescriptionEnGB"`
	LastModifiedBy          string      `json:"LastModifiedBy"`
	NameEnGB                string      `json:"NameEnGB"`
	LastModifiedOn          string      `json:"LastModifiedOn"`
	DescriptionZhCN         string      `json:"DescriptionZhCN"`
	CreatedBy               string      `json:"CreatedBy"`
	DescriptionLocalized    string      `json:"DescriptionLocalized"`
	DescriptionPtPT         string      `json:"DescriptionPtPT"`
}

type LocationNav struct {
	ExternalCode         string      `json:"ExternalCode"`
	StartDate            string      `json:"StartDate"`
	LastModifiedDateTime string      `json:"LastModifiedDateTime"`
	EndDate              string      `json:"EndDate"`
	StandardHours        string      `json:"StandardHours"`
	Timezone             string      `json:"Timezone"`
	LastModifiedBy       string      `json:"LastModifiedBy"`
	CreatedDateTime      string      `json:"CreatedDateTime"`
	Description          string      `json:"Description"`
	CreatedOn            string      `json:"CreatedOn"`
	LastModifiedOn       string      `json:"LastModifiedOn"`
	CreatedBy            string      `json:"CreatedBy"`
	Name                 string      `json:"Name"`
	GeozoneFlx           string      `json:"GeozoneFlx"`
	LocationGroup        string      `json:"LocationGroup"`
	Status               string      `json:"Status"`
}

type JobLevelNav struct {
	ExternalCode                 string      `json:"ExternalCode"`
	PickListV2EffectiveStartDate string      `json:"PickListV2EffectiveStartDate"`
	PickListV2ID                 string      `json:"PickListV2ID"`
	LabelNlNL                    string      `json:"LabelNlNL"`
	LastModifiedDateTime         string      `json:"LastModifiedDateTime"`
	MdfSystemEffectiveEndDate    string      `json:"MdfSystemEffectiveEndDate"`
	CreatedDateTime              string      `json:"CreatedDateTime"`
	MdfSystemVersionID           string      `json:"MdfSystemVersionID"`
	LabelEsES                    string      `json:"LabelEsES"`
	MaxVal                       string      `json:"MaxVal"`
	MinVal                       string      `json:"MinVal"`
	LabelPtBR                    string      `json:"LabelPtBR"`
	MdfSystemEntityID            string      `json:"MdfSystemEntityID"`
	LabelEnDEBUG                 string      `json:"LabelEnDEBUG"`
	NonUniqueExternalCode        string      `json:"NonUniqueExternalCode"`
	LegacyStatus                 string      `json:"LegacyStatus"`
	LabelRuRU                    string      `json:"LabelRuRU"`
	MdfSystemRecordStatus        string      `json:"MdfSystemRecordStatus"`
	LabelDefaultValue            string      `json:"LabelDefaultValue"`
	LabelEnUS                    string      `json:"LabelEnUS"`
	LabelDeDE                    string      `json:"LabelDeDE"`
	LabelLocalized               string      `json:"LabelLocalized"`
	LabelKoKR                    string      `json:"LabelKoKR"`
	OptionID                     string      `json:"OptionID"`
	Status                       string      `json:"Status"`
	OptValue                     string      `json:"OptValue"`
	LValue                       string      `json:"LValue"`
	MdfSystemEffectiveStartDate  string      `json:"MdfSystemEffectiveStartDate"`
	LabelZhTW                    string      `json:"LabelZhTW"`
	LabelJaJP                    string      `json:"LabelJaJP"`
	ExternalStandardizedCode     string      `json:"ExternalStandardizedCode"`
	MdfSystemObjectType          string      `json:"MdfSystemObjectType"`
	LabelPtPT                    string      `json:"LabelPtPT"`
	LastModifiedDate             string      `json:"LastModifiedDate"`
	LastModifiedBy               string      `json:"LastModifiedBy"`
	LastModifiedDateWithTZ       string      `json:"LastModifiedDateWithTZ"`
	LabelZhCN                    string      `json:"LabelZhCN"`
	RValue                       string      `json:"RValue"`
	MdfSystemTransactionSequence string      `json:"MdfSystemTransactionSequence"`
	CreatedDate                  string      `json:"CreatedDate"`
	CreatedBy                    string      `json:"CreatedBy"`
	ParentPickListValue          string      `json:"ParentPickListValue"`
	MdfSystemRecordID            string      `json:"MdfSystemRecordID"`
	LabelFrFR                    string      `json:"LabelFrFR"`
	LabelEnGB                    string      `json:"LabelEnGB"`
}

type CostCenterNav struct {
	ExternalCode               string      `json:"ExternalCode"`
	StartDate                  string      `json:"StartDate"`
	Parent                     string      `json:"Parent"`
	DescriptionKoKR            string      `json:"DescriptionKoKR"`
	LastModifiedDateTime       string      `json:"LastModifiedDateTime"`
	NameLocalized              string      `json:"NameLocalized"`
	EndDate                    string      `json:"EndDate"`
	EntityUUID                 string      `json:"EntityUUID"`
	NameKoKR                   string      `json:"NameKoKR"`
	CreatedDateTime            string      `json:"CreatedDateTime"`
	DescriptionPtBR            string      `json:"DescriptionPtBR"`
	DescriptionEsES            string      `json:"DescriptionEsES"`
	NamePtBR                   string      `json:"NamePtBR"`
	DescriptionNlNL            string      `json:"DescriptionNlNL"`
	NameNlNL                   string      `json:"NameNlNL"`
	DescriptionDefaultValue    string      `json:"DescriptionDefaultValue"`
	NameDeDE                   string      `json:"NameDeDE"`
	NameZhTW                   string      `json:"NameZhTW"`
	Name                       string      `json:"Name"`
	NameEsES                   string      `json:"NameEsES"`
	DescriptionEnUS            string      `json:"DescriptionEnUS"`
	GlStatementCode            string      `json:"GlStatementCode"`
	DescriptionEnDEBUG         string      `json:"DescriptionEnDEBUG"`
	DescriptionRuRU            string      `json:"DescriptionRuRU"`
	Status                     string      `json:"Status"`
	NameRuRU                   string      `json:"NameRuRU"`
	DescriptionJaJP            string      `json:"DescriptionJaJP"`
	DescriptionFrFR            string      `json:"DescriptionFrFR"`
	NamePtPT                   string      `json:"NamePtPT"`
	Description                string      `json:"Description"`
	DescriptionDeDE            string      `json:"DescriptionDeDE"`
	NameFrFR                   string      `json:"NameFrFR"`
	NameEnDEBUG                string      `json:"NameEnDEBUG"`
	NameJaJP                   string      `json:"NameJaJP"`
	CreatedOn                  string      `json:"CreatedOn"`
	NameEnUS                   string      `json:"NameEnUS"`
	DescriptionZhTW            string      `json:"DescriptionZhTW"`
	NameZhCN                   string      `json:"NameZhCN"`
	CostcenterExternalObjectID string      `json:"CostcenterExternalObjectID"`
	NameDefaultValue           string      `json:"NameDefaultValue"`
	DescriptionEnGB            string      `json:"DescriptionEnGB"`
	LastModifiedBy             string      `json:"LastModifiedBy"`
	NameEnGB                   string      `json:"NameEnGB"`
	LastModifiedOn             string      `json:"LastModifiedOn"`
	DescriptionZhCN            string      `json:"DescriptionZhCN"`
	CreatedBy                  string      `json:"CreatedBy"`
	DescriptionLocalized       string      `json:"DescriptionLocalized"`
	DescriptionPtPT            string      `json:"DescriptionPtPT"`
	CostcenterManager          string      `json:"CostcenterManager"`
}

type JobCodeNav struct {
	ExternalCode            string      `json:"ExternalCode"`
	StartDate               string      `json:"StartDate"`
	SupervisorLevel         string      `json:"SupervisorLevel"`
	NameKoKR                string      `json:"NameKoKR"`
	CreatedDateTime         string      `json:"CreatedDateTime"`
	CustString6PtPT         string      `json:"CustString6PtPT"`
	NamePtBR                string      `json:"NamePtBR"`
	CustString7JaJP         string      `json:"CustString7JaJP"`
	ParentJobCode           string      `json:"ParentJobCode"`
	WorkerCompCode          string      `json:"WorkerCompCode"`
	CustString6Localized    string      `json:"CustString6Localized"`
	CustString1DeDE         string      `json:"CustString1DeDE"`
	CustString7RuRU         string      `json:"CustString7RuRU"`
	CustString2FrFR         string      `json:"CustString2FrFR"`
	Grade                   string      `json:"Grade"`
	NameEsES                string      `json:"NameEsES"`
	CustString7DeDE         string      `json:"CustString7DeDE"`
	CustString1NlNL         string      `json:"CustString1NlNL"`
	IsFulltimeEmployee      bool        `json:"IsFulltimeEmployee"`
	CustString9EnGB         string      `json:"CustString9EnGB"`
	CustString8RuRU         string      `json:"CustString8RuRU"`
	NameEnUS                string      `json:"NameEnUS"`
	CustString2JaJP         string      `json:"CustString2JaJP"`
	JobFunction             string      `json:"JobFunction"`
	CustString1PtPT         string      `json:"CustString1PtPT"`
	DescriptionZhTW         string      `json:"DescriptionZhTW"`
	CustString1RuRU         string      `json:"CustString1RuRU"`
	NameZhCN                string      `json:"NameZhCN"`
	CustString2RuRU         string      `json:"CustString2RuRU"`
	CustString6DeDE         string      `json:"CustString6DeDE"`
	DescriptionEnGB         string      `json:"DescriptionEnGB"`
	CustString7PtPT         string      `json:"CustString7PtPT"`
	CustString6EsES         string      `json:"CustString6EsES"`
	NameEnGB                string      `json:"NameEnGB"`
	LastModifiedOn          string      `json:"LastModifiedOn"`
	CustString1JaJP         string      `json:"CustString1JaJP"`
	CustString2DefaultValue string      `json:"CustString2DefaultValue"`
	DescriptionZhCN         string      `json:"DescriptionZhCN"`
	CustString8JaJP         string      `json:"CustString8JaJP"`
	CustString9ZhTW         string      `json:"CustString9ZhTW"`
	CustString6EnUS         string      `json:"CustString6EnUS"`
	CustString6ZhCN         string      `json:"CustString6ZhCN"`
	DescriptionKoKR         string      `json:"DescriptionKoKR"`
	LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
	CustString9DefaultValue string      `json:"CustString9DefaultValue"`
	DescriptionPtBR         string      `json:"DescriptionPtBR"`
	CustString8EnGB         string      `json:"CustString8EnGB"`
	CustString6RuRU         string      `json:"CustString6RuRU"`
	CustString9EnUS         string      `json:"CustString9EnUS"`
	CustString9ZhCN         string      `json:"CustString9ZhCN"`
	CustString2PtPT         string      `json:"CustString2PtPT"`
	CustString8NlNL         string      `json:"CustString8NlNL"`
	RegularTemporary        string      `json:"RegularTemporary"`
	NameNlNL                string      `json:"NameNlNL"`
	CustString9JaJP         string      `json:"CustString9JaJP"`
	NameDeDE                string      `json:"NameDeDE"`
	NameZhTW                string      `json:"NameZhTW"`
	CustString7KoKR         string      `json:"CustString7KoKR"`
	Name                    string      `json:"Name"`
	CustString9Localized    string      `json:"CustString9Localized"`
	DescriptionRuRU         string      `json:"DescriptionRuRU"`
	NameRuRU                string      `json:"NameRuRU"`
	CustString6EnGB         string      `json:"CustString6EnGB"`
	NamePtPT                string      `json:"NamePtPT"`
	CustString5             string      `json:"CustString5"`
	CustString4             string      `json:"CustString4"`
	CustString3             string      `json:"CustString3"`
	CustString7NlNL         string      `json:"CustString7NlNL"`
	Description             string      `json:"Description"`
	DescriptionDeDE         string      `json:"DescriptionDeDE"`
	CustString8EnUS         string      `json:"CustString8EnUS"`
	CustString1FrFR         string      `json:"CustString1FrFR"`
	CustString6KoKR         string      `json:"CustString6KoKR"`
	EmployeeClass           string      `json:"EmployeeClass"`
	CustString7EnDEBUG      string      `json:"CustString7EnDEBUG"`
	DefaultSupervisorLevel  string      `json:"DefaultSupervisorLevel"`
	DefaultJobLevel         string      `json:"DefaultJobLevel"`
	CustString1DefaultValue string      `json:"CustString1DefaultValue"`
	CustString7ZhCN         string      `json:"CustString7ZhCN"`
	CustString1PtBR         string      `json:"CustString1PtBR"`
	CustString2DeDE         string      `json:"CustString2DeDE"`
	CustString6NlNL         string      `json:"CustString6NlNL"`
	CreatedBy               string      `json:"CreatedBy"`
	CustString9EsES         string      `json:"CustString9EsES"`
	CustString7EnGB         string      `json:"CustString7EnGB"`
	CustString6ZhTW         string      `json:"CustString6ZhTW"`
	DescriptionPtPT         string      `json:"DescriptionPtPT"`
	EndDate                 string      `json:"EndDate"`
	CustString2EsES         string      `json:"CustString2EsES"`
	CustString8KoKR         string      `json:"CustString8KoKR"`
	CustString7ZhTW         string      `json:"CustString7ZhTW"`
	CustString2PtBR         string      `json:"CustString2PtBR"`
	CustString1EnGB         string      `json:"CustString1EnGB"`
	DescriptionNlNL         string      `json:"DescriptionNlNL"`
	CustString9PtPT         string      `json:"CustString9PtPT"`
	CustString10            string      `json:"CustString10"`
	IsRegular               string      `json:"IsRegular"`
	CustString8EsES         string      `json:"CustString8EsES"`
	CustString2ZhCN         string      `json:"CustString2ZhCN"`
	CustString8ZhCN         string      `json:"CustString8ZhCN"`
	CustString7EnUS         string      `json:"CustString7EnUS"`
	CustString1ZhTW         string      `json:"CustString1ZhTW"`
	Status                  string      `json:"Status"`
	CustString7EsES         string      `json:"CustString7EsES"`
	CustString8PtPT         string      `json:"CustString8PtPT"`
	DescriptionFrFR         string      `json:"DescriptionFrFR"`
	NameFrFR                string      `json:"NameFrFR"`
	NameEnDEBUG             string      `json:"NameEnDEBUG"`
	CreatedOn               string      `json:"CreatedOn"`
	CustString8EnDEBUG      string      `json:"CustString8EnDEBUG"`
	CustString8ZhTW         string      `json:"CustString8ZhTW"`
	CustString2ZhTW         string      `json:"CustString2ZhTW"`
	CustString9RuRU         string      `json:"CustString9RuRU"`
	NameDefaultValue        string      `json:"NameDefaultValue"`
	CustString1EnDEBUG      string      `json:"CustString1EnDEBUG"`
	CustString9KoKR         string      `json:"CustString9KoKR"`
	JobLevel                string      `json:"JobLevel"`
	CustString2KoKR         string      `json:"CustString2KoKR"`
	CustString6DefaultValue string      `json:"CustString6DefaultValue"`
	CustString8DefaultValue string      `json:"CustString8DefaultValue"`
	CustString6EnDEBUG      string      `json:"CustString6EnDEBUG"`
	DefaultEmployeeClass    string      `json:"DefaultEmployeeClass"`
	CustString9NlNL         string      `json:"CustString9NlNL"`
	CustString2NlNL         string      `json:"CustString2NlNL"`
	NameLocalized           string      `json:"NameLocalized"`
	EntityUUID              string      `json:"EntityUUID"`
	CustString1KoKR         string      `json:"CustString1KoKR"`
	DescriptionEsES         string      `json:"DescriptionEsES"`
	CustString8Localized    string      `json:"CustString8Localized"`
	CustString1EsES         string      `json:"CustString1EsES"`
	CustString6FrFR         string      `json:"CustString6FrFR"`
	StandardHours           string      `json:"StandardHours"`
	CustString6PtBR         string      `json:"CustString6PtBR"`
	CustString9PtBR         string      `json:"CustString9PtBR"`
	DescriptionDefaultValue string      `json:"DescriptionDefaultValue"`
	CustString9FrFR         string      `json:"CustString9FrFR"`
	CustString2EnGB         string      `json:"CustString2EnGB"`
	CustString2Localized    string      `json:"CustString2Localized"`
	CustString9EnDEBUG      string      `json:"CustString9EnDEBUG"`
	CustString6JaJP         string      `json:"CustString6JaJP"`
	DescriptionEnUS         string      `json:"DescriptionEnUS"`
	DescriptionEnDEBUG      string      `json:"DescriptionEnDEBUG"`
	DescriptionJaJP         string      `json:"DescriptionJaJP"`
	CustString1ZhCN         string      `json:"CustString1ZhCN"`
	NameJaJP                string      `json:"NameJaJP"`
	CustString7Localized    string      `json:"CustString7Localized"`
	CustString8DeDE         string      `json:"CustString8DeDE"`
	CustString2EnDEBUG      string      `json:"CustString2EnDEBUG"`
	CustString7PtBR         string      `json:"CustString7PtBR"`
	CustString8FrFR         string      `json:"CustString8FrFR"`
	CustString1EnUS         string      `json:"CustString1EnUS"`
	LastModifiedBy          string      `json:"LastModifiedBy"`
	CustomString5           string      `json:"CustomString5"`
	CustomString4           string      `json:"CustomString4"`
	CustomString3           string      `json:"CustomString3"`
	CustomString2           string      `json:"CustomString2"`
	CustString9DeDE         string      `json:"CustString9DeDE"`
	CustomString9           string      `json:"CustomString9"`
	CustomString8           string      `json:"CustomString8"`
	CustomString7           string      `json:"CustomString7"`
	CustString1Localized    string      `json:"CustString1Localized"`
	CustomString6           string      `json:"CustomString6"`
	CustomString1           string      `json:"CustomString1"`
	CustString7DefaultValue string      `json:"CustString7DefaultValue"`
	DescriptionLocalized    string      `json:"DescriptionLocalized"`
	CustString2EnUS         string      `json:"CustString2EnUS"`
	CustString8PtBR         string      `json:"CustString8PtBR"`
	CustString7FrFR         string      `json:"CustString7FrFR"`
}

type DivisionNav struct {
	ExternalCode            string      `json:"ExternalCode"`
	StartDate               string      `json:"StartDate"`
	Parent                  string      `json:"Parent"`
	DescriptionKoKR         string      `json:"DescriptionKoKR"`
	LastModifiedDateTime    string      `json:"LastModifiedDateTime"`
	NameLocalized           string      `json:"NameLocalized"`
	EndDate                 string      `json:"EndDate"`
	EntityUUID              string      `json:"EntityUUID"`
	NameKoKR                string      `json:"NameKoKR"`
	CreatedDateTime         string      `json:"CreatedDateTime"`
	DescriptionPtBR         string      `json:"DescriptionPtBR"`
	DescriptionEsES         string      `json:"DescriptionEsES"`
	NamePtBR                string      `json:"NamePtBR"`
	DescriptionNlNL         string      `json:"DescriptionNlNL"`
	NameNlNL                string      `json:"NameNlNL"`
	DescriptionDefaultValue string      `json:"DescriptionDefaultValue"`
	NameDeDE                string      `json:"NameDeDE"`
	NameZhTW                string      `json:"NameZhTW"`
	Name                    string      `json:"Name"`
	NameEsES                string      `json:"NameEsES"`
	DescriptionEnUS         string      `json:"DescriptionEnUS"`
	DescriptionEnDEBUG      string      `json:"DescriptionEnDEBUG"`
	DescriptionRuRU         string      `json:"DescriptionRuRU"`
	Status                  string      `json:"Status"`
	NameRuRU                string      `json:"NameRuRU"`
	DescriptionJaJP         string      `json:"DescriptionJaJP"`
	DescriptionFrFR         string      `json:"DescriptionFrFR"`
	NamePtPT                string      `json:"NamePtPT"`
	Description             string      `json:"Description"`
	DescriptionDeDE         string      `json:"DescriptionDeDE"`
	NameFrFR                string      `json:"NameFrFR"`
	NameEnDEBUG             string      `json:"NameEnDEBUG"`
	NameJaJP                string      `json:"NameJaJP"`
	CreatedOn               string      `json:"CreatedOn"`
	HeadOfUnit              string      `json:"HeadOfUnit"`
	NameEnUS                string      `json:"NameEnUS"`
	DescriptionZhTW         string      `json:"DescriptionZhTW"`
	NameZhCN                string      `json:"NameZhCN"`
	NameDefaultValue        string      `json:"NameDefaultValue"`
	DescriptionEnGB         string      `json:"DescriptionEnGB"`
	LastModifiedBy          string      `json:"LastModifiedBy"`
	NameEnGB                string      `json:"NameEnGB"`
	LastModifiedOn          string      `json:"LastModifiedOn"`
	DescriptionZhCN         string      `json:"DescriptionZhCN"`
	CreatedBy               string      `json:"CreatedBy"`
	DescriptionLocalized    string      `json:"DescriptionLocalized"`
	DescriptionPtPT         string      `json:"DescriptionPtPT"`
}

type ParentPosition struct {
	Code                        string      `json:"Code"`
	EffectiveStartDate          string      `json:"EffectiveStartDate"`
	BusinessUnit                string      `json:"BusinessUnit"`
	LastModifiedDateTime        string      `json:"LastModifiedDateTime"`
	JobTitle                    string      `json:"JobTitle"`
	Criticality                 string      `json:"Criticality"`
	CreatedDateTime             string      `json:"CreatedDateTime"`
	JobCode                     string      `json:"JobCode"`
	MdfSystemVersionID          string      `json:"MdfSystemVersionID"`
	Type                        string      `json:"Type"`
	Incumbent                   string      `json:"Incumbent"`
	Division                    string      `json:"Division"`
	ExternalNameZhTW            string      `json:"ExternalNameZhTW"`
	ExternalNameJaJP            string      `json:"ExternalNameJaJP"`
	MdfSystemEntityID           string      `json:"MdfSystemEntityID"`
	PayRange                    string      `json:"PayRange"`
	RegularTemporary            string      `json:"RegularTemporary"`
	ExternalNamePtPT            string      `json:"ExternalNamePtPT"`
	CostCenter                  string      `json:"CostCenter"`
	StandardHours               string      `json:"StandardHours"`
	LegacyPositionID            string      `json:"LegacyPositionID"`
	ExternalNameZhCN            string      `json:"ExternalNameZhCN"`
	ExternalNameLocalized       string      `json:"ExternalNameLocalized"`
	MdfSystemRecordStatus       string      `json:"MdfSystemRecordStatus"`
	Vacant                      bool        `json:"Vacant"`
	EffectiveStatus             string      `json:"EffectiveStatus"`
	ExternalNameFrFR            string      `json:"ExternalNameFrFR"`
	TechnicalParameters         string      `json:"TechnicalParameters"`
	ExternalNameEnGB            string      `json:"ExternalNameEnGB"`
	EffectiveEndDate            string      `json:"EffectiveEndDate"`
	PositionCriticality         string      `json:"PositionCriticality"`
	ExternalNameNlNL            string      `json:"ExternalNameNlNL"`
	PositionTitle               string      `json:"PositionTitle"`
	Description                 string      `json:"Description"`
	ExternalNameDefaultValue    string      `json:"ExternalNameDefaultValue"`
	ExternalNameEsES            string      `json:"ExternalNameEsES"`
	PositionControlled          string      `json:"PositionControlled"`
	ExternalNamePtBR            string      `json:"ExternalNamePtBR"`
	PayGrade                    string      `json:"PayGrade"`
	Company                     string      `json:"Company"`
	Department                  string      `json:"Department"`
	EmployeeClass               string      `json:"EmployeeClass"`
	MdfSystemObjectType         string      `json:"MdfSystemObjectType"`
	CreationSource              string      `json:"CreationSource"`
	ChangeReason                string      `json:"ChangeReason"`
	TargetFTE                   string      `json:"TargetFTE"`
	LastModifiedDate            string      `json:"LastModifiedDate"`
	ExternalNameRuRU            string      `json:"ExternalNameRuRU"`
	LastModifiedBy              string      `json:"LastModifiedBy"`
	LastModifiedDateWithTZ      string      `json:"LastModifiedDateWithTZ"`
	JobLevel                    string      `json:"JobLevel"`
	TransactionSequence         string      `json:"TransactionSequence"`
	ExternalNameDeDE            string      `json:"ExternalNameDeDE"`
	ExternalNameKoKR            string      `json:"ExternalNameKoKR"`
	CreatedDate                 string      `json:"CreatedDate"`
	CreatedBy                   string      `json:"CreatedBy"`
	MdfSystemOptimisticLockUUID string      `json:"MdfSystemOptimisticLockUUID"`
	MdfSystemRecordID           string      `json:"MdfSystemRecordID"`
	Comment                     string      `json:"Comment"`
	Location                    string      `json:"Location"`
	MultipleIncumbentsAllowed   bool        `json:"MultipleIncumbentsAllowed"`
	ExternalNameEnUS            string      `json:"ExternalNameEnUS"`
	ExternalNameEnDEBUG         string      `json:"ExternalNameEnDEBUG"`
}

type PayGradeNav struct {
	ExternalCode              string      `json:"ExternalCode"`
	StartDate                 string      `json:"StartDate"`
	LastModifiedDateTime      string      `json:"LastModifiedDateTime"`
	EndDate                   string      `json:"EndDate"`
	LastModifiedBy            string      `json:"LastModifiedBy"`
	CreatedDateTime           string      `json:"CreatedDateTime"`
	Description               string      `json:"Description"`
	CreatedOn                 string      `json:"CreatedOn"`
	LastModifiedOn            string      `json:"LastModifiedOn"`
	PaygradeLevel             string      `json:"PaygradeLevel"`
	CustomString1             string      `json:"CustomString1"`
	CreatedBy                 string      `json:"CreatedBy"`
	Name                      string      `json:"Name"`
	Status                    string      `json:"Status"`
}
